### ISSUE TITLE
[SET]  nest-cli env compile path 수정, package.json script 수정, 동적 ConfigModule 등록 

### ISSUE THREAD

**Issue by de-novo** [pear-luk/Pearluk-Server#4]
## Description 
> Nest-cli.js 수정 ( env 경로 설정 ) 및 동적 ConfigModule 등록

## Progress
- [x] Nest-cli.js 수정 (env 경로 설정)
- [x] package.json script 수정
- [x] 동적 ConfigModule 등록

## ETC
> 기타사항

**Comment by iamjooon2** [comment]
멋찌다 디노보

**Comment by de-novo** [comment]
완료
